name: Run Tests and Generate Code Coverages

on:
  push:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install  tensorflow  # Add any necessary requirements

      - name: Run tests
        run: python -m unittest discover tests/

      - name: Collect code coverage data
        run: coverage run -m unittest discover tests/

      - name: Generate code coverage report
        run: coverage html -d coverage/

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/
