name: CI

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the Python version you're using

      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust the command as needed

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report -m
        env:
          COVERAGE_FILE: .coverage.ci  # Custom coverage file name

      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: .coverage.ci  # Match the coverage file name from above
